### ISSUE TITLE
When building from code transparency does not work

### ISSUE THREAD

**Issue by bq-wrongway** [SergioRibera/super_clipboard#10]
Hi,
i have downloaded your binary, (last one that you built) and when i use the binary i get transparency (on wayland), it works normal.
However, when i build from source, i get always black background, even if i did not change anything in your code itself.

I was also trying to accomplish same thing in iced myself, for small program i need, and i was unable, on xOrg or mac it works with no issues, on wayland it does not.
Your super_clipboard is the only thing i saw being transparent on wayland and made in iced, and im really curios what makes it work.

Thank you in advance

**Comment by SergioRibera** [comment]
Hello, thank you very much for using my reference projects, the answer is simple, the main branch uses `iced_tiny_skia` and it does not support transparencies, the reason why I use it is because using wgpu by default takes much more resources compared to `iced_tiny_skia`

**Comment by bq-wrongway** [comment]
I understand that , but even when using default uced settings i dont get transparency on wayland.
So i was wondering if you did something special with wgpu,or iced settings to make this work.
I did basic counter example, and on xorg and mac i get transparency with no issues and on wayland its always black. You are only person where i saw this working on Wayland.
edit:

glow renderer made it possible to have transparency, it worn work with skia
